#+STARTUP: latexpreview

(spacemacs/sort=>sorted-layers-list)

* How is Spacemacs Organized?
Spacemacs is stored in the Emacs dot directory (=.emacs.d=); however, the
Spacemacs configuration file may be stored in one of two places, with the first
taking precedence: =$HOME/.spacemacs= OR =$HOME/.spacemacs.d/init.el=.

Understand the difference between the identity and purpose of the initialization.
- =.spacemacs= $==$ =.spacemacs.d/init.el=
- =.spacemacs= $!=$ =.emacs.d/init.el=

** Synchronization of dotfile changes
To apply the modifications made in =~/.spacemacs= press ~SPC f e R~. It will
re-execute the Spacemacs initialization process.

*Note*: A synchronization re-executes the functions =dotspacemacs/init=,
=dotspacemacs/user-init= and =dotspacemacs/user-config=.
Depending on the contents of these functions, you may encounter some unwanted side
effects. For instance, if you use a toggle in =dotspacemac/user-config= to enable
some behavior, this behavior will be turned off whenever the dotfile is
re-synchronized. To avoid these side-effects, it is recommended to either use
=setq= expressions instead of toggle functions, or to use the =on= or =off=
versions instead (i.e. instead of =spacemacs/toggle-<thing>=, use
=spacemacs/toggle-<thing>-on= or =spacemacs/toggle-<thing>-off=).

It is possible to /skip/ the execution of =dotspacemacs/user-config= with the
universal argument (~SPC u SPC f e R~).

* How is Emacs organized?
